name: Commit Message Validation

on:
  push:
  pull_request:

jobs:
  lint-commit-message:
    name: Lint Commit Messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Commitlint
        run: npm install @commitlint/{config-conventional,cli} --save-dev

      - name: Lint commit message
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            npx commitlint --from=HEAD~1 --to=HEAD
          else
            echo "No previous commits to validate."
          fi
